# Generated by Django 5.2.4 on 2025-08-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('hash_arquivo', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('em_assinatura', 'Em Assinatura'), ('finalizado', 'Finalizado'), ('suspeito', 'Suspeito')], default='enviado', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('funcao', models.CharField(choices=[('usuario', 'Usuário'), ('admin', 'Administrador'), ('validador', 'Validador')], default='usuario', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caligrafia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_assinatura', models.CharField(max_length=255)),
                ('resultado_ocr', models.TextField(blank=True)),
                ('confianca', models.FloatField()),
                ('suspeita_falsificacao', models.BooleanField(default=False)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caligrafias', to='integrity.documento')),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_visualizar', models.BooleanField(default=False)),
                ('pode_assinar', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='integrity.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='integrity.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LogDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('ip_origem', models.CharField(max_length=45)),
                ('data_log', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrity.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrity.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_enviados', to='integrity.usuario'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_hash', models.CharField(max_length=255)),
                ('carimbo_tempo', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='integrity.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='integrity.usuario')),
            ],
        ),
    ]
