# Generated by Django 5.2.4 on 2025-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='caminho_arquivo',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
