# Generated by Django 5.2.4 on 2025-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrity', '0002_alter_documento_caminho_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
